version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: rushless_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rushless
      POSTGRES_PASSWORD: rushless
      POSTGRES_DB: rushless
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
